taco:
  orders:
    pageSize: 10

logging:
  level:
    tacos: DEBUG
    
spring:  jpa:    hibernate:      ddl-auto: none
      data:    rest:      base-path: /api
---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: tacouser
    password: tacopassword
  logging:
    level:
    tacos: WARN